name: cryptopals
description: Dart solution to the cryptopals challenges.
homepage: https://github.com/mobilecoinofficial/cryptopals-challenges
publish_to: none

environment:
  sdk: '>=2.17.3 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
